export interface GmProgramEntry {
    program: number
    name: string
    family: GmProgramFamily
}

export type GmProgramFamily =
    | "piano"
    | "chromatic-percussion"
    | "organ"
    | "guitar"
    | "bass"
    | "strings"
    | "ensemble"
    | "brass"
    | "reed"
    | "pipe"
    | "synth-lead"
    | "synth-pad"
    | "synth-effects"
    | "ethnic"
    | "percussive"
    | "sound-effects"
    | "drum"

export const GM_PROGRAMS: ReadonlyArray<GmProgramEntry> = [
    {program: 0, name: "Acoustic Grand Piano", family: "piano"},
    {program: 1, name: "Bright Acoustic Piano", family: "piano"},
    {program: 2, name: "Electric Grand Piano", family: "piano"},
    {program: 3, name: "Honky-tonk Piano", family: "piano"},
    {program: 4, name: "Electric Piano 1", family: "piano"},
    {program: 5, name: "Electric Piano 2", family: "piano"},
    {program: 6, name: "Harpsichord", family: "piano"},
    {program: 7, name: "Clavinet", family: "piano"},
    {program: 8, name: "Celesta", family: "chromatic-percussion"},
    {program: 9, name: "Glockenspiel", family: "chromatic-percussion"},
    {program: 10, name: "Music Box", family: "chromatic-percussion"},
    {program: 11, name: "Vibraphone", family: "chromatic-percussion"},
    {program: 12, name: "Marimba", family: "chromatic-percussion"},
    {program: 13, name: "Xylophone", family: "chromatic-percussion"},
    {program: 14, name: "Tubular Bells", family: "chromatic-percussion"},
    {program: 15, name: "Dulcimer", family: "chromatic-percussion"},
    {program: 16, name: "Drawbar Organ", family: "organ"},
    {program: 17, name: "Percussive Organ", family: "organ"},
    {program: 18, name: "Rock Organ", family: "organ"},
    {program: 19, name: "Church Organ", family: "organ"},
    {program: 20, name: "Reed Organ", family: "organ"},
    {program: 21, name: "Accordion", family: "organ"},
    {program: 22, name: "Harmonica", family: "organ"},
    {program: 23, name: "Tango Accordion", family: "organ"},
    {program: 24, name: "Acoustic Guitar (nylon)", family: "guitar"},
    {program: 25, name: "Acoustic Guitar (steel)", family: "guitar"},
    {program: 26, name: "Electric Guitar (jazz)", family: "guitar"},
    {program: 27, name: "Electric Guitar (clean)", family: "guitar"},
    {program: 28, name: "Electric Guitar (muted)", family: "guitar"},
    {program: 29, name: "Overdriven Guitar", family: "guitar"},
    {program: 30, name: "Distortion Guitar", family: "guitar"},
    {program: 31, name: "Guitar Harmonics", family: "guitar"},
    {program: 32, name: "Acoustic Bass", family: "bass"},
    {program: 33, name: "Electric Bass (finger)", family: "bass"},
    {program: 34, name: "Electric Bass (pick)", family: "bass"},
    {program: 35, name: "Fretless Bass", family: "bass"},
    {program: 36, name: "Slap Bass 1", family: "bass"},
    {program: 37, name: "Slap Bass 2", family: "bass"},
    {program: 38, name: "Synth Bass 1", family: "bass"},
    {program: 39, name: "Synth Bass 2", family: "bass"},
    {program: 40, name: "Violin", family: "strings"},
    {program: 41, name: "Viola", family: "strings"},
    {program: 42, name: "Cello", family: "strings"},
    {program: 43, name: "Contrabass", family: "strings"},
    {program: 44, name: "Tremolo Strings", family: "strings"},
    {program: 45, name: "Pizzicato Strings", family: "strings"},
    {program: 46, name: "Orchestral Harp", family: "strings"},
    {program: 47, name: "Timpani", family: "strings"},
    {program: 48, name: "String Ensemble 1", family: "ensemble"},
    {program: 49, name: "String Ensemble 2", family: "ensemble"},
    {program: 50, name: "Synth Strings 1", family: "ensemble"},
    {program: 51, name: "Synth Strings 2", family: "ensemble"},
    {program: 52, name: "Choir Aahs", family: "ensemble"},
    {program: 53, name: "Voice Oohs", family: "ensemble"},
    {program: 54, name: "Synth Voice", family: "ensemble"},
    {program: 55, name: "Orchestra Hit", family: "ensemble"},
    {program: 56, name: "Trumpet", family: "brass"},
    {program: 57, name: "Trombone", family: "brass"},
    {program: 58, name: "Tuba", family: "brass"},
    {program: 59, name: "Muted Trumpet", family: "brass"},
    {program: 60, name: "French Horn", family: "brass"},
    {program: 61, name: "Brass Section", family: "brass"},
    {program: 62, name: "Synth Brass 1", family: "brass"},
    {program: 63, name: "Synth Brass 2", family: "brass"},
    {program: 64, name: "Soprano Sax", family: "reed"},
    {program: 65, name: "Alto Sax", family: "reed"},
    {program: 66, name: "Tenor Sax", family: "reed"},
    {program: 67, name: "Baritone Sax", family: "reed"},
    {program: 68, name: "Oboe", family: "reed"},
    {program: 69, name: "English Horn", family: "reed"},
    {program: 70, name: "Bassoon", family: "reed"},
    {program: 71, name: "Clarinet", family: "reed"},
    {program: 72, name: "Piccolo", family: "pipe"},
    {program: 73, name: "Flute", family: "pipe"},
    {program: 74, name: "Recorder", family: "pipe"},
    {program: 75, name: "Pan Flute", family: "pipe"},
    {program: 76, name: "Blown Bottle", family: "pipe"},
    {program: 77, name: "Shakuhachi", family: "pipe"},
    {program: 78, name: "Whistle", family: "pipe"},
    {program: 79, name: "Ocarina", family: "pipe"},
    {program: 80, name: "Lead 1 (square)", family: "synth-lead"},
    {program: 81, name: "Lead 2 (sawtooth)", family: "synth-lead"},
    {program: 82, name: "Lead 3 (calliope)", family: "synth-lead"},
    {program: 83, name: "Lead 4 (chiff)", family: "synth-lead"},
    {program: 84, name: "Lead 5 (charang)", family: "synth-lead"},
    {program: 85, name: "Lead 6 (voice)", family: "synth-lead"},
    {program: 86, name: "Lead 7 (fifths)", family: "synth-lead"},
    {program: 87, name: "Lead 8 (bass + lead)", family: "synth-lead"},
    {program: 88, name: "Pad 1 (new age)", family: "synth-pad"},
    {program: 89, name: "Pad 2 (warm)", family: "synth-pad"},
    {program: 90, name: "Pad 3 (polysynth)", family: "synth-pad"},
    {program: 91, name: "Pad 4 (choir)", family: "synth-pad"},
    {program: 92, name: "Pad 5 (bowed)", family: "synth-pad"},
    {program: 93, name: "Pad 6 (metallic)", family: "synth-pad"},
    {program: 94, name: "Pad 7 (halo)", family: "synth-pad"},
    {program: 95, name: "Pad 8 (sweep)", family: "synth-pad"},
    {program: 96, name: "FX 1 (rain)", family: "synth-effects"},
    {program: 97, name: "FX 2 (soundtrack)", family: "synth-effects"},
    {program: 98, name: "FX 3 (crystal)", family: "synth-effects"},
    {program: 99, name: "FX 4 (atmosphere)", family: "synth-effects"},
    {program: 100, name: "FX 5 (brightness)", family: "synth-effects"},
    {program: 101, name: "FX 6 (goblins)", family: "synth-effects"},
    {program: 102, name: "FX 7 (echoes)", family: "synth-effects"},
    {program: 103, name: "FX 8 (sci-fi)", family: "synth-effects"},
    {program: 104, name: "Sitar", family: "ethnic"},
    {program: 105, name: "Banjo", family: "ethnic"},
    {program: 106, name: "Shamisen", family: "ethnic"},
    {program: 107, name: "Koto", family: "ethnic"},
    {program: 108, name: "Kalimba", family: "ethnic"},
    {program: 109, name: "Bagpipe", family: "ethnic"},
    {program: 110, name: "Fiddle", family: "ethnic"},
    {program: 111, name: "Shanai", family: "ethnic"},
    {program: 112, name: "Tinkle Bell", family: "percussive"},
    {program: 113, name: "Agogo", family: "percussive"},
    {program: 114, name: "Steel Drums", family: "percussive"},
    {program: 115, name: "Woodblock", family: "percussive"},
    {program: 116, name: "Taiko Drum", family: "percussive"},
    {program: 117, name: "Melodic Tom", family: "percussive"},
    {program: 118, name: "Synth Drum", family: "percussive"},
    {program: 119, name: "Reverse Cymbal", family: "percussive"},
    {program: 120, name: "Guitar Fret Noise", family: "sound-effects"},
    {program: 121, name: "Breath Noise", family: "sound-effects"},
    {program: 122, name: "Seashore", family: "sound-effects"},
    {program: 123, name: "Bird Tweet", family: "sound-effects"},
    {program: 124, name: "Telephone Ring", family: "sound-effects"},
    {program: 125, name: "Helicopter", family: "sound-effects"},
    {program: 126, name: "Applause", family: "sound-effects"},
    {program: 127, name: "Gunshot", family: "sound-effects"},
    {program: 128, name: "Drum Kit", family: "drum"},
]

export const findGmProgram = (program: number): GmProgramEntry | undefined =>
    GM_PROGRAMS.find(entry => entry.program === program)